# --- SERVER AYARLARI (CLOUD RUN İÇİN) ---
server.address=0.0.0.0
server.port=${PORT:8080}

# --- DATABASE AYARLARI (GOOGLE CLOUD) ---

# 1. Adres: Localhost yerine Google Cloud IP'sini yazıyoruz (Görselden aldım)
# Not: Sondaki '/postgres' varsayılan veritabanı adıdır.
spring.datasource.url=jdbc:postgresql://35.233.83.137:5432/postgres

# 2. Kullanıcı Adı: Google Cloud'da genelde 'postgres'tir.
spring.datasource.username=postgres

# 3. Şifre: BURASI ÇOK ÖNEMLİ!
# Buraya '1' yazma. Google Cloud'da veritabanını ilk oluştururken belirlediğin "root password"ü yaz.
spring.datasource.password=omER4613/

# --- HIBERNATE AYARLARI (Aynı Kalabilir) ---
# Bu ayar sayesinde tabloların Google Cloud'da otomatik oluşur.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- MAIL AYARLARI (Burası Aynen Kalsın) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=stackademy41@gmail.com
spring.mail.password=ulxz tugc iywh megg 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Spring MVC Path Matcher (Cloud Run uyumlulugu icin)
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Dosya Yükleme Limitleri (Video için artırdık)
spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB